version: '3.8'

services:
  adversarial-data-gen:
    build:
      context: ../adversarial-data-gen
      dockerfile: Dockerfile
    user: core
    networks:
      - app-network

  threat-intelligence:
    build:
      context: ./threat-intelligence
      dockerfile: Dockerfile
    user: core
    networks:
      - app-network

networks:
  app-network:
    driver: bridge